"""Runtime configuration for the Voice Perception Service."""

from __future__ import annotations

import os

SAMPLE_RATE = 16_000
CHANNELS = 1
CHUNK_SECONDS = 1.0
MIN_INFERENCE_SECONDS = 0.2
MIN_INFERENCE_SAMPLES = int(SAMPLE_RATE * MIN_INFERENCE_SECONDS)
LIVE_ROLLING_CONTEXT_SECONDS = float(os.getenv("LIVE_ROLLING_CONTEXT_SECONDS", "5.0"))
LIVE_MIN_CONTEXT_SECONDS = float(os.getenv("LIVE_MIN_CONTEXT_SECONDS", "2.0"))
LIVE_CONTEXT_GRACE_SECONDS = float(os.getenv("LIVE_CONTEXT_GRACE_SECONDS", "0.05"))
LIVE_INFERENCE_HOP_SECONDS = float(os.getenv("LIVE_INFERENCE_HOP_SECONDS", "1.0"))
LIVE_HOP_GRACE_SECONDS = float(os.getenv("LIVE_HOP_GRACE_SECONDS", "0.05"))
LIVE_ROLLING_SAMPLES = max(
    MIN_INFERENCE_SAMPLES,
    int(SAMPLE_RATE * LIVE_ROLLING_CONTEXT_SECONDS),
)
LIVE_MIN_CONTEXT_SAMPLES = max(
    MIN_INFERENCE_SAMPLES,
    int(SAMPLE_RATE * max(0.0, LIVE_MIN_CONTEXT_SECONDS - LIVE_CONTEXT_GRACE_SECONDS)),
)
LIVE_INFERENCE_HOP_SAMPLES = max(
    1,
    int(SAMPLE_RATE * max(0.0, LIVE_INFERENCE_HOP_SECONDS - LIVE_HOP_GRACE_SECONDS)),
)

SENSEVOICE_MODEL_DIR = os.getenv("SENSEVOICE_MODEL_DIR", "iic/SenseVoiceSmall-onnx")
SENSEVOICE_CACHE_DIR = os.getenv("SENSEVOICE_CACHE_DIR", ".cache/modelscope")
SENSEVOICE_QUANTIZE = os.getenv("SENSEVOICE_QUANTIZE", "true").lower() not in {
    "0",
    "false",
    "no",
}
SENSEVOICE_DEVICE_ID = os.getenv("SENSEVOICE_DEVICE_ID", "-1")
SENSEVOICE_THREADS = int(os.getenv("SENSEVOICE_THREADS", "4"))
SENSEVOICE_LANGUAGE = os.getenv("SENSEVOICE_LANGUAGE", "auto").strip().lower() or "auto"

GERMAN_ASR_ENABLED = os.getenv("GERMAN_ASR_ENABLED", "true").lower() not in {"0", "false", "no"}
GERMAN_ASR_MODEL = os.getenv("GERMAN_ASR_MODEL", "Systran/faster-whisper-base")
GERMAN_ASR_COMPUTE_TYPE = os.getenv("GERMAN_ASR_COMPUTE_TYPE", "int8")
GERMAN_ASR_THREADS = int(os.getenv("GERMAN_ASR_THREADS", "4"))
GERMAN_ASR_PRELOAD = os.getenv("GERMAN_ASR_PRELOAD", "false").lower() not in {
    "0",
    "false",
    "no",
}
GERMAN_ASR_MIN_CONTEXT_SECONDS = float(os.getenv("GERMAN_ASR_MIN_CONTEXT_SECONDS", "2.0"))
GERMAN_ASR_MIN_CONTEXT_SAMPLES = max(
    MIN_INFERENCE_SAMPLES,
    int(SAMPLE_RATE * GERMAN_ASR_MIN_CONTEXT_SECONDS),
)
GERMAN_ASR_BEAM_SIZE = int(os.getenv("GERMAN_ASR_BEAM_SIZE", "1"))

SER_ENABLED = os.getenv("SER_ENABLED", "true").lower() not in {"0", "false", "no"}
SER_MODEL_DIR = os.getenv("SER_MODEL_DIR", "iic/emotion2vec_plus_base")
SER_CACHE_DIR = os.getenv("SER_CACHE_DIR", ".cache/modelscope")
SER_THREADS = int(os.getenv("SER_THREADS", "4"))
SER_PRELOAD = os.getenv("SER_PRELOAD", "true").lower() not in {"0", "false", "no"}
SER_MIN_CONTEXT_SECONDS = float(os.getenv("SER_MIN_CONTEXT_SECONDS", "1.0"))
SER_MIN_CONTEXT_SAMPLES = max(
    MIN_INFERENCE_SAMPLES,
    int(SAMPLE_RATE * SER_MIN_CONTEXT_SECONDS),
)
SER_LICENSE_CAVEAT = "hackathon_demo_license_pending"
LIVE_EMOTION_NEW_LABEL_UPDATES = int(os.getenv("LIVE_EMOTION_NEW_LABEL_UPDATES", "2"))
LIVE_EMOTION_NEUTRAL_UPDATES = int(os.getenv("LIVE_EMOTION_NEUTRAL_UPDATES", "2"))
LIVE_EMOTION_NEUTRAL_CONFIDENCE = float(os.getenv("LIVE_EMOTION_NEUTRAL_CONFIDENCE", "0.75"))
LIVE_EMOTION_STRONG_CONFIDENCE = float(os.getenv("LIVE_EMOTION_STRONG_CONFIDENCE", "0.65"))
LIVE_EMOTION_HOLD_SECONDS = float(os.getenv("LIVE_EMOTION_HOLD_SECONDS", "2.0"))
LIVE_EMOTION_IMMEDIATE_SWITCH_CONFIDENCE = float(
    os.getenv("LIVE_EMOTION_IMMEDIATE_SWITCH_CONFIDENCE", "0.92")
)
LIVE_EMOTION_IMMEDIATE_SWITCH_MARGIN = float(os.getenv("LIVE_EMOTION_IMMEDIATE_SWITCH_MARGIN", "0.25"))

ACOUSTIC_FRAME_MS = int(os.getenv("ACOUSTIC_FRAME_MS", "20"))
ACOUSTIC_HOP_MS = int(os.getenv("ACOUSTIC_HOP_MS", "10"))
ACOUSTIC_PITCH_FRAME_MS = int(os.getenv("ACOUSTIC_PITCH_FRAME_MS", "40"))
ACOUSTIC_MIN_SPEECH_SECONDS = float(os.getenv("ACOUSTIC_MIN_SPEECH_SECONDS", "0.08"))
ACOUSTIC_BASELINE_ENERGY_DB = float(os.getenv("ACOUSTIC_BASELINE_ENERGY_DB", "-28.0"))
ACOUSTIC_BASELINE_ENERGY_IQR_DB = float(os.getenv("ACOUSTIC_BASELINE_ENERGY_IQR_DB", "8.0"))
ACOUSTIC_BASELINE_F0_RANGE_ST = float(os.getenv("ACOUSTIC_BASELINE_F0_RANGE_ST", "6.0"))
ACOUSTIC_BASELINE_RATE = float(os.getenv("ACOUSTIC_BASELINE_RATE", "3.5"))
ACOUSTIC_BASELINE_PAUSE_RATIO = float(os.getenv("ACOUSTIC_BASELINE_PAUSE_RATIO", "0.12"))
ACOUSTIC_SIGNAL_DEBUG = os.getenv("ACOUSTIC_SIGNAL_DEBUG", "true").lower() not in {
    "0",
    "false",
    "no",
}
ACOUSTIC_HESITATION_FUSION_WEIGHT = float(os.getenv("ACOUSTIC_HESITATION_FUSION_WEIGHT", "0.65"))
ACOUSTIC_STRESS_FUSION_WEIGHT = float(os.getenv("ACOUSTIC_STRESS_FUSION_WEIGHT", "0.35"))

EMOTION_STRESS = {
    "FEARFUL": 0.9,
    "SAD": 0.6,
    "ANGRY": 0.5,
    "DISGUSTED": 0.4,
    "SURPRISED": 0.3,
    "NEUTRAL": 0.1,
    "HAPPY": 0.0,
}
EVENT_STRESS = {
    "Breath": 0.3,
    "Cough": 0.4,
    "Cry": 0.5,
}
EVENT_STRESS_MAX = 0.8
SILENCE_STRESS_MULTIPLIER = 0.5
HESITATION_EMOTION_WEIGHT = 0.5
HESITATION_EVENT_WEIGHT = 0.3
HESITATION_SILENCE_WEIGHT = 0.2
HESITATION_EMA_ALPHA = 0.4

SILENCE_RMS_THRESHOLD = float(os.getenv("SILENCE_RMS_THRESHOLD", "0.01"))
SILENCE_FRAME_MS = int(os.getenv("SILENCE_FRAME_MS", "20"))
NO_SPEECH_RMS_THRESHOLD = float(os.getenv("NO_SPEECH_RMS_THRESHOLD", "0.005"))
NO_SPEECH_MIN_NON_SILENT_RATIO = float(os.getenv("NO_SPEECH_MIN_NON_SILENT_RATIO", "0.04"))
NO_SPEECH_MIN_NON_SILENT_SECONDS = float(os.getenv("NO_SPEECH_MIN_NON_SILENT_SECONDS", "0.20"))

SESSION_TTL_SECONDS = int(os.getenv("SESSION_TTL_SECONDS", "600"))
SESSION_SWEEP_SECONDS = int(os.getenv("SESSION_SWEEP_SECONDS", "30"))
TRANSCRIPT_MAX_CHARS = int(os.getenv("TRANSCRIPT_MAX_CHARS", "2000"))
MAX_AUDIO_BUFFER_BYTES = int(os.getenv("MAX_AUDIO_BUFFER_BYTES", str(50 * 1024 * 1024)))
